launch: Fix launching selfbot on Python>=3.10 environment
loop= parameter in asyncio.gather() has been removed with Python 3.10, having
been deprecated since 3.8 due to behaviorial changes introduced with 3.7.

Traceback (most recent call last):
  File "/home/userbot/pyrobud/main.py", line 5, in <module>
    main.main()
  File "/home/userbot/pyrobud/pyrobud/main.py", line 27, in main
    launch.main(config_path=args.config_path)
  File "/home/userbot/pyrobud/pyrobud/launch.py", line 68, in main
    aiorun.run(_upgrade(config, config_path), stop_on_unhandled_errors=True, loop=loop)
  File "/home/userbot/.userbot310/lib/python3.10/site-packages/aiorun.py", line 325, in run
    group = gather(*tasks, *do_not_cancel, loop=loop, return_exceptions=True)
TypeError: gather() got an unexpected keyword argument 'loop'

Try running the selfbot without loop= first, before trying the one with it, for
as long as Python 3.6<=x<3.8 remains supported by the project.

Signed-off-by: Albert I <kras@raphielgang.org>